=== RickyDenton/SSE-Anomaly-Detection-in-Manufacturing/datasegregation/configuration/configuration.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "preparationPackage": {
      "type": "string"
    },
    "preparedFeaturesPath": {
      "type": "string"
    },
    "classBalancingReport": {
      "type": "string"
    },
    "featureSpaceAnomalousReport": {
      "type": "string"
    },
    "featureSpaceRegularReport": {
      "type": "string"
    },
    "trainingSetPath": {
      "type": "string"
    },
    "validationSetPath": {
      "type": "string"
    },
    "testSetPath": {
      "type": "string"
    },
    "minimumNumberOfFeatures": {
      "type": "integer",
      "minimum": 3
    },
    "trainingSetSize": {
      "type": "integer",
      "minimum": 1,
      "maximum": 100
    },
    "validationSetSize": {
      "type": "integer",
      "minimum": 1,
      "maximum": 100
    },
    "testSetSize": {
      "type": "integer",
      "minimum": 1,
      "maximum": 100
    },
    "classBalanceThreshold": {
      "type": "integer",
      "minimum": 0,
      "maximum": 100
    }
  },
  "required": [
    "preparationPackage",
    "preparedFeaturesPath",
    "classBalancingReport",
    "featureSpaceAnomalousReport",
    "featureSpaceRegularReport",
    "trainingSetPath",
    "validationSetPath",
    "testSetPath",
    "minimumNumberOfFeatures",
    "trainingSetSize",
    "validationSetSize",
    "testSetSize",
    "classBalanceThreshold"
  ],
  "additionalProperties": false
}

=== RickyDenton/SSE-Anomaly-Detection-in-Manufacturing/datasegregation/configuration/configuration.json
{
  "preparationPackage": "datapreparation",
  "preparedFeaturesPath": "output/features.csv",
  "classBalancingReport": "output/classBalancing.png",
  "featureSpaceAnomalousReport": "output/featureSpaceAnomalous.png",
  "featureSpaceRegularReport": "output/featureSpaceRegular.png",
  "trainingSetPath": "output/training.csv",
  "validationSetPath": "output/validation.csv",
  "testSetPath": "output/test.csv",
  "minimumNumberOfFeatures": 100,
  "trainingSetSize": 70,
  "validationSetSize": 15,
  "testSetSize": 15,
  "classBalanceThreshold": 50
}
