=== RickyDenton/SSE-Anomaly-Detection-in-Manufacturing/anomalydetectionandperformance/configuration/configuration.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "dataPreparationPackage": {
      "type": "string"
    },
     "candidateModelPackage": {
      "type": "string"
    },
     "candidateModelDataPath": {
      "type": "string"
    },
    "featureDataPath": {
      "type": "string"
    },
    "anomaliesDetectedCountDataPath": {
      "type": "string"
    },
    "anomaliesForWeekDataPath": {
      "type": "string"
    },
    "detectedAnomaliesDataPath": {
      "type": "string"
    },
    "inputPath": {
      "type": "string"
    },
    "recalibrateModelScore": {
      "type": "number"
    }
  },
  "required": [
    "recalibrateModelScore",
    "inputPath",
    "dataPreparationPackage",
    "candidateModelPackage",
    "candidateModelDataPath",
    "featureDataPath",
    "detectedAnomaliesDataPath",
    "anomaliesForWeekDataPath",
    "anomaliesDetectedCountDataPath"
  ]
}

=== RickyDenton/SSE-Anomaly-Detection-in-Manufacturing/anomalydetectionandperformance/configuration/configuration.json
{
  "dataPreparationPackage": "datapreparation",
  "candidateModelPackage": "candidatemodelevaluation",
  "candidateModelDataPath": "output/candidate_model.sav",
  "featureDataPath": "output/features.csv",
  "anomaliesDetectedCountDataPath" : "output/anomaliesDetectedCount.png",
  "anomaliesForWeekDataPath" : "output/anomaliesForWeeks.png",
  "detectedAnomaliesDataPath" : "output/detectedAnomalies.csv",
  "inputPath" : "input",
  "recalibrateModelScore" : 0.8
}
